name: testing-yaml

on:
  #schedule:
    #- cron: '* * * * *'
  workflow_dispatch: 
    
jobs:
  wis-death-evals:
    runs-on: ubuntu-latest
    
    env: 
      GITHUB_PAT: ${{ testingsecret }}
      
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master
 
    - name: Install packages
      run: |
       # R -e 'install.packages("tidyverse")'
       # R -e 'install.packages("epiDisplay")'
       # R -e 'install.packages("MMWRweek")'
       # R -e 'install.packages("DT")'
       # R -e 'install.packages("plotly")'
    - name: Render document
      run: |
        source("testing.rmd")


