name: testing-yaml

on:
  #schedule:
    #- cron: '* * * * *'
  workflow_dispatch: 
    
jobs:
  wis-death-evals:
    runs-on: ubuntu-latest
    
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master
    - uses: r-lib/actions/setup-pandoc@v1
 
    - name: Install packages
      run: |
       # R -e 'install.packages("tidyverse")'
       # R -e 'install.packages("epiDisplay")'
       # R -e 'install.packages("MMWRweek")'
       # R -e 'install.packages("DT")'
       # R -e 'install.packages("plotly")'
       
       
    - name: Install rmarkdown
      run: Rscript -e 'install.packages("rmarkdown")'
    - name: Render README
      run: Rscript -e 'rmarkdown::render("testing.rmd", output_format = "html_document")'
    - name: Commit results
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git commit -m 'Testing html' || echo "No changes to commit"
        git push origin || echo "No changes to commit"


